Repository sous-chefs/line, pull requests merged in 2018-05, with the labels that each got.

#94 Add CircleCI Support (Danger)
  .circleci/config.yml
  .travis.yml
  appveyor.yml
Labels: Type: Maintenance

#97 Version 2.0.0
  CHANGELOG.md
  metadata.rb
  resources/replace_or_add.rb
Labels: Type: Feature Request

#103 Missing file
  CHANGELOG.md
  libraries/helper.rb
  libraries/os.rb
  resources/add_to_list.rb
  resources/append_if_no_line.rb
  resources/delete_from_list.rb
  resources/delete_lines.rb
  resources/replace_or_add.rb
  test/fixtures/cookbooks/test/recipes/append_if_no_line.rb
Labels: Type: Maintenance

#105 Fix markdown rendering for trailing whitespace
  README.md
Labels: Type: Documentation

#107 Add CODEOWNERS and github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODEOWNERS
Labels: Type: Documentation

#108 Documentation
  CONTRIBUTING.md
  TESTING.md
  chefignore
Labels: Type: Documentation
