Repository sous-chefs/line, pull requests merged in 2018-10, with the labels that each got.

#121 Add the filter_lines resource
  .kitchen.yml
  CHANGELOG.md
  README.md
  libraries/after_filter.rb
  libraries/filter_helper.rb
  libraries/helper.rb
  metadata.rb
  resources/filter_lines.rb
  spec/unit/library/filter/after_spec.rb
  spec/unit/library/filter/expand_spec.rb
  spec/unit/library/filter/missing_line_between_spec.rb
  spec/unit/library/helper_spec.rb
  test/fixtures/cookbooks/test/recipes/filter_lines_after.rb
  test/fixtures/cookbooks/test/recipes/filter_lines_inline.rb
  test/integration/filter_lines/controls/filter_lines_after_spec.rb
  test/integration/filter_lines/controls/filter_lines_inline_spec.rb
  test/integration/filter_lines/inspec.yml
Labels: Enhancement, Type: Feature Request

#122 issue_120: Allow the backup property to be specified as true
  CHANGELOG.md
  libraries/helper.rb
  resources/add_to_list.rb
  resources/append_if_no_line.rb
  resources/delete_from_list.rb
  resources/delete_lines.rb
  resources/filter_lines.rb
  resources/replace_or_add.rb
  test/fixtures/cookbooks/test/recipes/add_to_list.rb
  test/fixtures/cookbooks/test/recipes/append_if_no_line.rb
  test/fixtures/cookbooks/test/recipes/delete_from_list.rb
  test/fixtures/cookbooks/test/recipes/delete_lines.rb
  test/fixtures/cookbooks/test/recipes/filter_lines_after.rb
  test/fixtures/cookbooks/test/recipes/replace_or_add.rb
  test/integration/replace_or_add/controls/replace_or_add_add_a_line_matching_pattern.rb
Labels: Type: Bug, Type: Maintenance

#127 Add dokken workflow in circleci & remove travis
  .circleci/config.yml
  .kitchen.appveyor.yml
  .kitchen.dokken.yml
  .kitchen.yml
  CHANGELOG.md
Labels: Type: Maintenance
