Repository sous-chefs/line, pull requests merged in 2018-03, with the labels that each got.

#74 rework append_if_no_line to use file provider subresource
  CHANGELOG.md
  resources/append_if_no_line.rb
  test/fixtures/cookbooks/test/recipes/append_if_no_line.rb
  test/integration/append_if_no_line/inspec/controls/append_if_no_line_spec.rb
Labels: Type: Bug, Type: Maintenance

#75 Rework delete_lines resource to use file sub-resource
  CHANGELOG.md
  README.md
  resources/delete_lines.rb
  test/fixtures/cookbooks/test/recipes/delete_lines.rb
  test/integration/delete_lines/inspec/delete_lines.rb
Labels: Type: Bug

#78 Remove library helpers.
  CHANGELOG.md
  libraries/default.rb
  resources/add_to_list.rb
  resources/append_if_no_line.rb
  resources/delete_from_list.rb
  resources/replace_or_add.rb
  test/fixtures/cookbooks/test/files/dangerfile3
  test/fixtures/cookbooks/test/recipes/delete_from_list.rb
  test/integration/delete_from_list/inspec/delete_from_list_spec.rb
Labels: Type: Maintenance
