Repository sous-chefs/line, pull requests merged in 2021-09, with the labels that each got.

#228 Automated PR: Cookstyle Changes
  CHANGELOG.md
  resources/delete_from_list.rb
Labels: Release: Minor

#229 Update comment.md
  documentation/resources/filters/comment.md
Labels: Release: Patch

#230 Update comment.md
  CHANGELOG.md
  documentation/resources/filters/comment.md
Labels: Documentation, Release: Patch
