Repository sous-chefs/line, pull requests merged in 2022-06, with the labels that each got.

#237 Stanza slash
  .github/workflows/ci.yml
  CHANGELOG.md
  libraries/stanza_filter.rb
  spec/fixtures/cookbooks/spectest/metadata.rb
  test/fixtures/cookbooks/test/recipes/filter_lines_stanza.rb
  test/integration/filter_lines/controls/filter_lines_stanza.rb
Labels: Priority: Medium, Release: Minor

#235 Automated PR: Standardising Files
  CHANGELOG.md
  chefignore
Labels: Release: Patch, Skip: Announcements

#238 Stanza slash
  CHANGELOG.md
  spec/unit/library/filter/stanza_spec.rb
Labels: Priority: Low, Release: Patch
